### ISSUE TITLE
al registrar alumno en una actividad en el combo de actividad, sólo mostrar actividades del catálogo y quitar la opción todos.

### ISSUE THREAD

**Issue by lMarcoss** [lMarcoss/CalculadoraBecasFront#17]
![Captura de Pantalla 2020-03-25 a la(s) 12 30 43](https://user-images.githubusercontent.com/16256405/77572375-7aa3ed00-6e94-11ea-99b0-fdcb516be20a.png)

Revisa que en esa lista que estás enviando al combo genérico no agregues la opción all

**Comment by lperzh** [comment]
Se elimina la opción "TODOS"
<img width="853" alt="imagen" src="https://user-images.githubusercontent.com/11420317/80324750-e234bb80-87f7-11ea-98c5-5830a1ac6aeb.png">
